<template>
    <div>
         <v-form>
                <v-text-field
                  prepend-icon="person"
                  name="userName"
                  label="Name"
                  id="userName"
                  type="text"
                ></v-text-field>
                <v-text-field
                  prepend-icon="info"
                  name="userInfo"
                  label="Info"
                  id="userInfo"
                  type="text"
                ></v-text-field>
                <v-text-field
                  prepend-icon="email"
                  name="userEmail"
                  label="Email"
                  id="userEmail"
                  type="text"
                ></v-text-field>
                <v-text-field
                  prepend-icon="phone"
                  name="userPhone"
                  label="Phone Number"
                  id="userPhone"
                  mask="+### ## ###-###"
                ></v-text-field>
              </v-form>
    </div>
</template>